name: distrobuilder
base: core22
version: git
grade: devel
summary: System container image builder for LXC and LXD
description: |-
  Distrobuilder is a tool which lets you create container images for LXC and LXD.
license: Apache-2.0
confinement: classic

apps:
  distrobuilder:
    command: bin/distrobuilder

parts:
  distrobuilder:
    source: https://github.com/lxc/distrobuilder
    source-type: git
    build-attributes:
      - enable-patchelf
    build-packages:
      - gcc
    build-snaps:
      - go
    plugin: go
