name: lxd-imagebuilder
base: core24
version: git
grade: devel
summary: System container and VM image builder for LXD
description: |-
  LXD image builder is a tool which lets you create system container and VM images for use with LXD.
license: AGPL-3.0
confinement: classic

apps:
  lxd-imagebuilder:
    command: bin/lxd-imagebuilder

  simplestream-maintainer:
    command: bin/simplestream-maintainer

parts:
  lxd-imagebuilder:
    source: https://github.com/canonical/lxd-imagebuilder
    source-depth: 1
    source-type: git
    build-attributes:
      - enable-patchelf
    build-snaps:
      - go
    plugin: go

  strip:
    after:
      - lxd-imagebuilder
    plugin: nil
    override-prime: |
      set -x

      # Strip binaries
      find "${CRAFT_PRIME}"/bin -type f \
        -exec strip -s {} +
